name: GitHub issue repro
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "sudo apt-get install qemu binfmt-support qemu-user-static"
      - run: sudo apt-get install qemu binfmt-support qemu-user-static
